### ISSUE TITLE
App crashes when I try to open a video

### ISSUE THREAD

**Issue by justinjohn0306** [arichornlover/uYouEnhanced#485] opened 2024-03-27 06:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you read the FAQ?

- [X] Yes, I did read the FAQ

### iOS/iPadOS version

iOS 17.4.1

### Device model

iPhone 15 Pro Max

### Sideload tool

MapleSign

### Tweak version

uYouEnhanced_19.12.3-3.0.3.ipa

### Describe the bug

The app instantly crashes when I try to open a video, although it runs fine in preview mode

### Steps to reproduce the issue

1. Open the app
2. Search for a video 
3. Open the video

### Are you using the newest version of uYouPlus? If not, why?

✅ Yes, I'm using the latest version of uYouPlus right now

### Does the issue happen with the official YouTube from AppStore?

❌ No, I can't reproduce this issue in the official YouTube from AppStore

**Comment by mtshare** [comment] 2024-03-27 07:49
Same here

**Comment by preindex** [comment] 2024-03-27 08:26
I have the same issue. It appears that SponsorBlock is the issue.

If you want to keep using the app, disable Sponsorblock for now; something's wrong with it.

**Comment by mtshare** [comment] 2024-03-27 08:33
@preindex yes, by disabling SponsorBlock fix the problem. Thanks.

**Comment by justinjohn0306** [comment] 2024-03-27 08:37
> > I have the same issue. It appears that SponsorBlock is the issue.
> > If you want to keep using the app, disable Sponsorblock for now; something's wrong with it.
> 
> I’ve tried disabling it as well but no luck so far

Oh wait, it actually worked

**Comment by justinjohn0306** [comment] 2024-03-27 08:56
PiP mode is bugged out tho

**Comment by Diaub** [comment] 2024-03-27 09:42
I have the same issue on iPhone 15 Pro iOS 17.2.1 YTE 19.10.5-3.0-F1

I've tried changing iSponsoBlock and Youtube ads to disabled and the app still crashes after a start playing a video. Also tried uninstalling and reinstalling.

**Comment by Hexishu** [comment] 2024-03-27 12:09
So sponsorblock needs a fix?

**Comment by asportnoy** [comment] 2024-03-27 13:14
Duplicate of #484

**Comment by Altstor** [comment] 2024-03-27 13:56
> I have the same issue on iPhone 15 Pro iOS 17.2.1 YTE 19.10.5-3.0-F1
> 
> Disabling iSponsorblock fixes the issue.

No it does not

**Comment by Diaub** [comment] 2024-03-28 16:25
> > I have the same issue on iPhone 15 Pro iOS 17.2.1 YTE 19.10.5-3.0-F1
> 
> > 
> 
> > Disabling iSponsorblock fixes the issue.
> 
> 
> 
> No it does not

Did you make sure to disable iSponsorblock, close the application entirely, and then re-open?

I originally thought disabling iSponsorblock didn't work either, but that's because I didn't restart the app to refresh the setting.

**Comment by timoz1705** [comment] 2024-04-18 11:44
> > > I have the same issue on iPhone 15 Pro iOS 17.2.1 YTE 19.10.5-3.0-F1
> > 
> > 
> > > 
> > 
> > 
> > > Disabling iSponsorblock fixes the issue.
> > 
> > 
> > No it does not
> 
> Did you make sure to disable iSponsorblock, close the application entirely, and then re-open?
> 
> I originally thought disabling iSponsorblock didn't work either, but that's because I didn't restart the app to refresh the setting.


Tried it, still crashes for me.

iPhone 15 Pro, iOS17.4.1, YTE 19.14.2-3.0.3

**Closed** 2024-05-11 09:29 UTC
Labels: bug
